version: 1
labels:
- label: "type/feature"
  title: "^feat*"
- label: "type/fix"
  title: "^fix*"
- label: "type/refactor"
  title: "^refactor*"
- label: "type/style"
  title: "^style*"
- label: "type/chore"
  title: "^chore*"
- label: "type/perf"
  title: "^perf*"
- label: "type/build"
  title: "^build*"
- label: "type/revert"
  title: "^revert*"
- label: "component/ci"
  title: "^(ci*|[a-z]*(ci))*"
- label: "component/test"
  title: "^test*"
- label: "component/doc"
  title: "^doc*"
- label: "component/registry"
  title: "^[a-z]*(registry).*"
- label: "component/transformation"
  title: "^[a-z]*(transformation).*"
- label: "component/serving"
  title: "^[a-z]*(serving).*"
- label: "component/connector"
  title: "^[a-z]*(connector).*"
- label: "component/query"
  title: "^[a-z]*(query).*"
- label: "rust"
  files:
  - "src/*"
- label: "python"
  files:
  - "python/*"
