version: "3"

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_server_bolt_advertised_address=localhost:7687
      - NEO4j_server_http_advertised_address=localhost:7474
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - EXTENSION_SCRIPT=/var/lib/neo4j/import/import.sh
    volumes:
      # - ./neo4j_env/data:/var/lib/neo4j/data
      - ./neo4j_env/import:/var/lib/neo4j/import
    healthcheck:
      test: [ 'CMD-SHELL', 'neo4j status' ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 30s
      timeout: 10s
      retries: 3
    # environment:
    #   - REDIS_HOST=redis

  etcd:
    image: quay.io/coreos/etcd:v3.5.8
    container_name: etcd
    ports:
      - "2379:2379" # Client communication
      - "2380:2380" # Server-to-server communication
    command: |
      /usr/local/bin/etcd
      --name=etcd0
      --advertise-client-urls=http://etcd:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-advertise-peer-urls=http://etcd:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-cluster=etcd0=http://etcd:2380
    healthcheck:
      test: [ 'CMD', 'etcdctl', 'endpoint', 'health' ]
      interval: 30s
      timeout: 10s
      retries: 3

  demo:
    platform: linux/amd64
    build:
      context: ../..
    image: ofnil-demo
    container_name: ofnil-quickstart
    depends_on:
      - neo4j
      - redis
      - etcd
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: ./examples/quickstart/docker_entry.sh
    volumes:
      - ofnil:/ofnil

volumes:
  ofnil:
    name: ofnil-data
